name: test work
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
  repository_dispatch:
    types:
      - test
jobs:
  check:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
