name: test2_name
on:
  repository_dispatch:
    types:
      - configuration-check
jobs:
  check:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
